export const colors = {
    PRIMARY_COLORS: '#266691',
    SECONDARY_COLORS: '#002651',
    BORDER_COLORS: '#dbdbdb',
    WATER_COLORS: '#00CCFF',
    PRESSURE_COLORS : '#330000',
    WINDY_COLORS :'#CCCCCC',
}